In [38]:
import pandas as pd
df=pd.read_csv("avocado.csv")

In [39]:
df.head()

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [40]:
df.drop('Unnamed: 0', axis=1,inplace=True)
Albany_df = df[df['region']=='Albany']
Albany_df.set_index('Date', inplace=True)
Albany_df.head()

,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
Date,,,,,,,,,,,,
2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [26]:
df['region'].unique()

array(['Albany', 'Atlanta', 'BaltimoreWashington', 'Boise', 'Boston',
       'BuffaloRochester', 'California', 'Charlotte', 'Chicago',
       'CincinnatiDayton', 'Columbus', 'DallasFtWorth', 'Denver',
       'Detroit', 'GrandRapids', 'GreatLakes', 'HarrisburgScranton',
       'HartfordSpringfield', 'Houston', 'Indianapolis', 'Jacksonville',
       'LasVegas', 'LosAngeles', 'Louisville', 'MiamiFtLauderdale',
       'Midsouth', 'Nashville', 'NewOrleansMobile', 'NewYork',
       'Northeast', 'NorthernNewEngland', 'Orlando', 'Philadelphia',
       'PhoenixTucson', 'Pittsburgh', 'Plains', 'Portland',
       'RaleighGreensboro', 'RichmondNorfolk', 'Roanoke', 'Sacramento',
       'SanDiego', 'SanFrancisco', 'Seattle', 'SouthCarolina',
       'SouthCentral', 'Southeast', 'Spokane', 'StLouis', 'Syracuse',
       'Tampa', 'TotalUS', 'West', 'WestTexNewMexico'], dtype=object)

In [41]:
Chicago_df=df[df['region']=='Chicago']

In [42]:
Chicago_df.set_index('Date', inplace=True)
Chicago_df.head()
Chicago_df.head()

,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
Date,,,,,,,,,,,,
2015-12-27,0.93,661137.13,42799.00,445218.79,78378.25,94741.09,83066.75,1617.67,10056.67,conventional,2015,Chicago
2015-12-20,0.91,690669.34,35724.99,464574.15,96306.30,94063.90,76241.25,9592.65,8230.00,conventional,2015,Chicago
2015-12-13,1.07,668601.50,40380.09,451470.42,94162.53,82588.46,76829.42,5693.75,65.29,conventional,2015,Chicago
2015-12-06,1.14,664020.49,53173.18,455048.11,92888.37,62910.83,62473.12,420.95,16.76,conventional,2015,Chicago
2015-11-29,1.11,602481.22,42851.47,422479.32,74988.97,62161.46,61862.57,298.89,0.00,conventional,2015,Chicago

In [43]:
concated=pd.concat([Albany_df,Chicago_df],keys=['Albany','Chicago'])

In [44]:
concated

                    AveragePrice  Total Volume     4046       4225     4770  \
        Date
Albany  2015-12-27          1.33      64236.62  1036.74   54454.85    48.16
        2015-12-20          1.35      54876.98   674.28   44638.81    58.33
        2015-12-13          0.93     118220.22   794.70  109149.67   130.50
        2015-12-06          1.08      78992.15  1132.00   71976.41    72.58
        2015-11-29          1.28      51039.60   941.48   43838.39    75.78
        2015-11-22          1.26      55979.78  1184.27   48067.99    43.61
        2015-11-15          0.99      83453.76  1368.92   73672.72    93.26
        2015-11-08          0.98     109428.33   703.75  101815.36    80.00
        2015-11-01          1.02      99811.42  1022.15   87315.57    85.34
        2015-10-25          1.07      74338.76   842.40   64757.44   113.00
        2015-10-18          1.12      84843.44   924.86   75595.85   117.07
        2015-10-11          1.28      64489.17  1582.03   52677.92   105.32
        2015-10-04          1.31      61007.10  2268.32   49880.67   101.36
        2015-09-27          0.99     106803.39  1204.88   99409.21   154.84
        2015-09-20          1.33      69759.01  1028.03   59313.12   150.50
        2015-09-13          1.28      76111.27   985.73   65696.86   142.00
        2015-09-06          1.11      99172.96   879.45   90062.62   240.79
        2015-08-30          1.07     105693.84   689.01   94362.67   335.43
        2015-08-23          1.34      79992.09   733.16   67933.79   444.78
        2015-08-16          1.33      80043.78   539.65   68666.01   394.90
        2015-08-09          1.12     111140.93   584.63  100961.46   368.95
        2015-08-02          1.45      75133.10   509.94   62035.06   741.08
        2015-07-26          1.11     106757.10   648.75   91949.05   966.61
        2015-07-19          1.26      96617.00  1042.10   82049.40  2238.02
        2015-07-12          1.05     124055.31   672.25   94693.52  4257.64
        2015-07-05          1.35     109252.12   869.45   72600.55  5883.16
        2015-06-28          1.37      89534.81   664.23   57545.79  4662.71
        2015-06-21          1.27     104849.39   804.01   76688.55  5481.18
        2015-06-14          1.32      89631.30   850.58   55400.94  4377.19
        2015-06-07          1.07     122743.06   656.71   99220.82    90.32
...                          ...           ...      ...        ...      ...
Chicago 2017-04-30          1.97      46274.23    39.74   44553.79     0.00
        2017-04-23          1.67      50574.88   144.02   46354.05     0.00
        2017-04-16          1.74      68194.97   189.55   63660.83     0.00
        2017-04-09          1.95      57024.53   298.80   53040.02     0.00
        2017-04-02          1.94      56046.88   538.54   51259.58     0.00
        2017-03-26          1.67      48330.46  1252.26   43428.38     0.00
        2017-03-19          1.68      45989.07  1720.14   40737.11     0.00
        2017-03-12          1.93      33185.31   262.35   29577.44     0.00
        2017-03-05          1.64      47884.05   444.51   42428.17     0.00
        2017-02-26          1.69      46602.16   799.29   37768.66     0.00
        2017-02-19          1.60      36645.70   324.96   28155.69     0.00
        2017-02-12          1.53      35870.49    49.00   32792.61     0.00
        2017-02-05          1.49      42439.11    82.09   39288.55     0.00
        2017-01-29          1.51      44735.40    87.33   40554.73     0.00
        2017-01-22          1.51      47561.03    52.69   43587.09     0.00
        2017-01-15          1.85      38542.50    78.31   34378.08     0.00
        2017-01-08          1.81      28099.34    70.76   23893.31     0.00
        2017-01-01          1.34      36915.87    36.67   34076.57     0.00
        2018-03-25          1.69      35088.36   324.87   27550.29     0.00
        2018-03-18          1.66      35542.17   184.53   26955.74     0.00
        2018-03-11          1.66      41969.83   583.18   32382.95     0.00
        2018-03-04          1.62      46026.58  1107.05   35255.03     0.00
        2018-02-25          1.68      36432.65   246.73   29263.75     0.00
        2018-02-18          1.66      33678.58   259.18   24314.04     0.00
        2018-02-11          1.65      38202.17   409.68   26524.51     0.00
        2018-02-04          1.62      46956.84   313.29   32668.25     0.00
        2018-01-28          1.72      40770.94   215.40   31318.93     0.00
        2018-01-21          1.82      36688.67    83.93   28134.16     0.00
        2018-01-14          1.79      44955.89   133.39   31177.44     0.00
        2018-01-07          1.83      41573.25   118.84   29600.36     0.00

                    Total Bags  Small Bags  Large Bags  XLarge Bags  \
        Date
Albany  2015-12-27     8696.87     8603.62       93.25         0.00
        2015-12-20     9505.56     9408.07       97.49         0.00
        2015-12-13     8145.35     8042.21      103.14         0.00
        2015-12-06     5811.16     5677.40      133.76         0.00
        2015-11-29     6183.95     5986.26      197.69         0.00
        2015-11-22     6683.91     6556.47      127.44         0.00
        2015-11-15     8318.86     8196.81      122.05         0.00
        2015-11-08     6829.22     6266.85      562.37         0.00
        2015-11-01    11388.36    11104.53      283.83         0.00
        2015-10-25     8625.92     8061.47      564.45         0.00
        2015-10-18     8205.66     7877.86      327.80         0.00
        2015-10-11    10123.90     9866.27      257.63         0.00
        2015-10-04     8756.75     8379.98      376.77         0.00
        2015-09-27     6034.46     5888.87      145.59         0.00
        2015-09-20     9267.36     8489.10      778.26         0.00
        2015-09-13     9286.68     8665.19      621.49         0.00
        2015-09-06     7990.10     7762.87      227.23         0.00
        2015-08-30    10306.73    10218.93       87.80         0.00
        2015-08-23    10880.36    10745.79      134.57         0.00
        2015-08-16    10443.22    10297.68      145.54         0.00
        2015-08-09     9225.89     9116.34      109.55         0.00
        2015-08-02    11847.02    11768.52       78.50         0.00
        2015-07-26    13192.69    13061.53      131.16         0.00
        2015-07-19    11287.48    11103.49      183.99         0.00
        2015-07-12    24431.90    24290.08      108.49        33.33
        2015-07-05    29898.96    29663.19      235.77         0.00
        2015-06-28    26662.08    26311.76      350.32         0.00
        2015-06-21    21875.65    21662.00      213.65         0.00
        2015-06-14    29002.59    28343.14      659.45         0.00
        2015-06-07    22775.21    22314.99      460.22         0.00
...                        ...         ...         ...          ...
Chicago 2017-04-30     1680.70     1680.70        0.00         0.00
        2017-04-23     4076.81     4072.37        4.44         0.00
        2017-04-16     4344.59     4344.59        0.00         0.00
        2017-04-09     3685.71     3685.71        0.00         0.00
        2017-04-02     4248.76     4248.76        0.00         0.00
        2017-03-26     3649.82     3645.38        4.44         0.00
        2017-03-19     3531.82     3527.38        4.44         0.00
        2017-03-12     3345.52     3345.52        0.00         0.00
        2017-03-05     5011.37     5011.37        0.00         0.00
        2017-02-26     8034.21     8029.77        4.44         0.00
        2017-02-19     8165.05     8165.05        0.00         0.00
        2017-02-12     3028.88     3028.88        0.00         0.00
        2017-02-05     3068.47     3068.47        0.00         0.00
        2017-01-29     4093.34     4088.90        4.44         0.00
        2017-01-22     3921.25     3921.25        0.00         0.00
        2017-01-15     4086.11     4086.11        0.00         0.00
        2017-01-08     4135.27     4135.27        0.00         0.00
        2017-01-01     2802.63     2802.63        0.00         0.00
        2018-03-25     7213.20     7176.54       36.66         0.00
        2018-03-18     8401.90     8398.57        3.33         0.00
        2018-03-11     9003.70     8990.36       13.34         0.00
        2018-03-04     9664.50     9654.50       10.00         0.00
        2018-02-25     6922.17     6908.84       13.33         0.00
        2018-02-18     9105.36     9095.36       10.00         0.00
        2018-02-11    11267.98    11261.31        6.67         0.00
        2018-02-04    13975.30    13975.30        0.00         0.00
        2018-01-28     9236.61     9236.61        0.00         0.00
        2018-01-21     8470.58     8470.58        0.00         0.00
        2018-01-14    13645.06    13635.06       10.00         0.00
        2018-01-07    11854.05    11850.72        3.33         0.00

                            type  year   region
        Date
Albany  2015-12-27  conventional  2015   Albany
        2015-12-20  conventional  2015   Albany
        2015-12-13  conventional  2015   Albany
        2015-12-06  conventional  2015   Albany
        2015-11-29  conventional  2015   Albany
        2015-11-22  conventional  2015   Albany
        2015-11-15  conventional  2015   Albany
        2015-11-08  conventional  2015   Albany
        2015-11-01  conventional  2015   Albany
        2015-10-25  conventional  2015   Albany
        2015-10-18  conventional  2015   Albany
        2015-10-11  conventional  2015   Albany
        2015-10-04  conventional  2015   Albany
        2015-09-27  conventional  2015   Albany
        2015-09-20  conventional  2015   Albany
        2015-09-13  conventional  2015   Albany
        2015-09-06  conventional  2015   Albany
        2015-08-30  conventional  2015   Albany
        2015-08-23  conventional  2015   Albany
        2015-08-16  conventional  2015   Albany
        2015-08-09  conventional  2015   Albany
        2015-08-02  conventional  2015   Albany
        2015-07-26  conventional  2015   Albany
        2015-07-19  conventional  2015   Albany
        2015-07-12  conventional  2015   Albany
        2015-07-05  conventional  2015   Albany
        2015-06-28  conventional  2015   Albany
        2015-06-21  conventional  2015   Albany
        2015-06-14  conventional  2015   Albany
        2015-06-07  conventional  2015   Albany
...                          ...   ...      ...
Chicago 2017-04-30       organic  2017  Chicago
        2017-04-23       organic  2017  Chicago
        2017-04-16       organic  2017  Chicago
        2017-04-09       organic  2017  Chicago
        2017-04-02       organic  2017  Chicago
        2017-03-26       organic  2017  Chicago
        2017-03-19       organic  2017  Chicago
        2017-03-12       organic  2017  Chicago
        2017-03-05       organic  2017  Chicago
        2017-02-26       organic  2017  Chicago
        2017-02-19       organic  2017  Chicago
        2017-02-12       organic  2017  Chicago
        2017-02-05       organic  2017  Chicago
        2017-01-29       organic  2017  Chicago
        2017-01-22       organic  2017  Chicago
        2017-01-15       organic  2017  Chicago
        2017-01-08       organic  2017  Chicago
        2017-01-01       organic  2017  Chicago
        2018-03-25       organic  2018  Chicago
        2018-03-18       organic  2018  Chicago
        2018-03-11       organic  2018  Chicago
        2018-03-04       organic  2018  Chicago
        2018-02-25       organic  2018  Chicago
        2018-02-18       organic  2018  Chicago
        2018-02-11       organic  2018  Chicago
        2018-02-04       organic  2018  Chicago
        2018-01-28       organic  2018  Chicago
        2018-01-21       organic  2018  Chicago
        2018-01-14       organic  2018  Chicago
        2018-01-07       organic  2018  Chicago

[676 rows x 12 columns]

In [50]:
merged=pd.merge(Albany_df,Chicago_df,on='type',how='outer')
merged

,AveragePrice_x,Total Volume_x,4046_x,4225_x,4770_x,Total Bags_x,Small Bags_x,Large Bags_x,XLarge Bags_x,type,...,Total Volume_y,4046_y,4225_y,4770_y,Total Bags_y,Small Bags_y,Large Bags_y,XLarge Bags_y,year_y,region_y
0,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,661137.13,42799.00,445218.79,78378.25,94741.09,83066.75,1617.67,10056.67,2015,Chicago
1,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,690669.34,35724.99,464574.15,96306.30,94063.90,76241.25,9592.65,8230.00,2015,Chicago
2,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,668601.50,40380.09,451470.42,94162.53,82588.46,76829.42,5693.75,65.29,2015,Chicago
3,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,664020.49,53173.18,455048.11,92888.37,62910.83,62473.12,420.95,16.76,2015,Chicago
4,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,602481.22,42851.47,422479.32,74988.97,62161.46,61862.57,298.89,0.00,2015,Chicago
5,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,751897.89,34868.50,553545.31,89732.33,73751.75,73457.31,294.44,0.00,2015,Chicago
6,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,641881.96,31286.11,441753.60,93857.48,74984.77,74723.66,261.11,0.00,2015,Chicago
7,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,711146.61,44528.42,498562.41,101889.32,66166.46,65842.08,324.38,0.00,2015,Chicago
8,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,807041.46,69420.04,562214.56,106536.92,68869.94,68447.93,422.01,0.00,2015,Chicago
9,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,687650.27,59161.08,454352.60,108012.41,66124.18,65795.24,323.33,5.61,2015,Chicago
10,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,690302.58,25883.13,482992.35,118311.09,63116.01,62076.66,285.56,753.79,2015,Chicago
11,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,708914.17,16455.46,503813.92,119996.31,68648.48,65144.93,528.99,2974.56,2015,Chicago
12,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,675172.63,14268.84,485262.12,105711.40,69930.27,66015.29,2240.14,1674.84,2015,Chicago
13,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,720501.55,16483.95,532028.74,101193.84,70795.02,63370.36,2923.19,4501.47,2015,Chicago
14,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,729117.42,16477.56,534644.45,103103.75,74891.66,71195.89,3316.58,379.19,2015,Chicago
15,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,775671.49,17172.26,546965.49,128619.66,82914.08,78368.45,3809.54,736.09,2015,Chicago
16,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,808677.78,17595.54,581941.46,122938.43,86202.35,82905.34,3289.62,7.39,2015,Chicago
17,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,773773.53,17363.14,570147.23,112344.22,73918.94,71627.03,2205.32,86.59,2015,Chicago
18,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,751850.01,17595.95,550359.51,103622.38,80272.17,77073.51,2759.79,438.87,2015,Chicago
19,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,817690.89,19193.94,609692.45,104997.44,83807.06,80018.54,3447.81,340.71,2015,Chicago
20,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,731125.01,18237.36,526303.06,104796.41,81788.18,79510.48,1904.80,372.90,2015,Chicago
21,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,761027.42,21607.12,559825.17,97419.33,82175.80,79197.97,2476.30,501.53,2015,Chicago
22,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,791332.34,26653.29,577460.34,99066.58,88152.13,83728.75,3516.34,907.04,2015,Chicago
23,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,797060.27,20534.84,560871.56,116910.43,98743.44,92362.71,3531.27,2849.46,2015,Chicago
24,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,772151.20,22933.92,545739.34,109149.46,94328.48,90428.86,2536.23,1363.39,2015,Chicago
25,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,937317.45,28422.72,661207.19,118634.70,129052.84,126579.11,2236.49,237.24,2015,Chicago
26,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,786250.22,27391.54,524476.99,104595.10,129786.59,126835.70,1896.33,1054.56,2015,Chicago
27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,804902.52,34715.08,536926.08,122239.65,111021.71,107242.86,1658.76,2120.09,2015,Chicago
28,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,868197.41,55227.59,586037.06,107908.15,119024.61,116318.18,2618.95,87.48,2015,Chicago
29,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,...,824216.23,51410.51,544663.98,122929.34,105212.40,99942.37,4693.09,576.94,2015,Chicago
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57092,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,46274.23,39.74,44553.79,0.00,1680.70,1680.70,0.00,0.00,2017,Chicago
57093,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,50574.88,144.02,46354.05,0.00,4076.81,4072.37,4.44,0.00,2017,Chicago
57094,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,68194.97,189.55,63660.83,0.00,4344.59,4344.59,0.00,0.00,2017,Chicago
57095,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,57024.53,298.80,53040.02,0.00,3685.71,3685.71,0.00,0.00,2017,Chicago
57096,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,56046.88,538.54,51259.58,0.00,4248.76,4248.76,0.00,0.00,2017,Chicago
57097,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,48330.46,1252.26,43428.38,0.00,3649.82,3645.38,4.44,0.00,2017,Chicago
57098,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,45989.07,1720.14,40737.11,0.00,3531.82,3527.38,4.44,0.00,2017,Chicago
57099,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,33185.31,262.35,29577.44,0.00,3345.52,3345.52,0.00,0.00,2017,Chicago
57100,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,47884.05,444.51,42428.17,0.00,5011.37,5011.37,0.00,0.00,2017,Chicago
57101,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,46602.16,799.29,37768.66,0.00,8034.21,8029.77,4.44,0.00,2017,Chicago
57102,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,36645.70,324.96,28155.69,0.00,8165.05,8165.05,0.00,0.00,2017,Chicago
57103,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,35870.49,49.00,32792.61,0.00,3028.88,3028.88,0.00,0.00,2017,Chicago
57104,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,42439.11,82.09,39288.55,0.00,3068.47,3068.47,0.00,0.00,2017,Chicago
57105,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,44735.40,87.33,40554.73,0.00,4093.34,4088.90,4.44,0.00,2017,Chicago
57106,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,47561.03,52.69,43587.09,0.00,3921.25,3921.25,0.00,0.00,2017,Chicago
57107,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,38542.50,78.31,34378.08,0.00,4086.11,4086.11,0.00,0.00,2017,Chicago
57108,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,28099.34,70.76,23893.31,0.00,4135.27,4135.27,0.00,0.00,2017,Chicago
57109,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,36915.87,36.67,34076.57,0.00,2802.63,2802.63,0.00,0.00,2017,Chicago
57110,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,35088.36,324.87,27550.29,0.00,7213.20,7176.54,36.66,0.00,2018,Chicago
57111,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,35542.17,184.53,26955.74,0.00,8401.90,8398.57,3.33,0.00,2018,Chicago
57112,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,41969.83,583.18,32382.95,0.00,9003.70,8990.36,13.34,0.00,2018,Chicago
57113,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,46026.58,1107.05,35255.03,0.00,9664.50,9654.50,10.00,0.00,2018,Chicago
57114,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,36432.65,246.73,29263.75,0.00,6922.17,6908.84,13.33,0.00,2018,Chicago
57115,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,33678.58,259.18,24314.04,0.00,9105.36,9095.36,10.00,0.00,2018,Chicago
57116,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,38202.17,409.68,26524.51,0.00,11267.98,11261.31,6.67,0.00,2018,Chicago
57117,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,46956.84,313.29,32668.25,0.00,13975.30,13975.30,0.00,0.00,2018,Chicago
57118,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,40770.94,215.40,31318.93,0.00,9236.61,9236.61,0.00,0.00,2018,Chicago
57119,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,36688.67,83.93,28134.16,0.00,8470.58,8470.58,0.00,0.00,2018,Chicago
57120,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,44955.89,133.39,31177.44,0.00,13645.06,13635.06,10.00,0.00,2018,Chicago
57121,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,...,41573.25,118.84,29600.36,0.00,11854.05,11850.72,3.33,0.00,2018,Chicago