In [21]:
import pandas as pd

df=pd.read_csv('avocado.csv')
df.head()

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [22]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.head()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [23]:
df[df['AveragePrice']>1.35]

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
21,2015-08-02,1.45,75133.10,509.94,62035.06,741.08,11847.02,11768.52,78.50,0.00,conventional,2015,Albany
26,2015-06-28,1.37,89534.81,664.23,57545.79,4662.71,26662.08,26311.76,350.32,0.00,conventional,2015,Albany
32,2015-05-17,1.43,109857.47,1150.55,81955.16,94.32,26657.44,26285.43,372.01,0.00,conventional,2015,Albany
261,2015-12-20,1.37,90867.51,1164.92,38430.71,106.67,51165.21,51165.21,0.00,0.00,conventional,2015,BuffaloRochester
264,2015-11-29,1.39,79973.14,1514.69,35682.71,113.49,42662.25,42662.25,0.00,0.00,conventional,2015,BuffaloRochester
265,2015-11-22,1.40,90242.31,1711.77,38780.66,107.53,49642.35,49642.35,0.00,0.00,conventional,2015,BuffaloRochester
266,2015-11-15,1.36,99703.72,1803.78,41457.12,107.48,56335.34,55593.12,742.22,0.00,conventional,2015,BuffaloRochester
269,2015-10-25,1.36,99554.55,1545.57,36645.91,79.64,61283.43,59381.21,1902.22,0.00,conventional,2015,BuffaloRochester
274,2015-09-20,1.54,60624.47,1445.25,39831.66,88.61,19258.95,18437.84,821.11,0.00,conventional,2015,BuffaloRochester
275,2015-09-13,1.59,73043.20,1572.71,48468.73,134.33,22867.43,22421.87,445.56,0.00,conventional,2015,BuffaloRochester
276,2015-09-06,1.56,76139.58,1471.69,49388.48,173.32,25106.09,25092.76,13.33,0.00,conventional,2015,BuffaloRochester
277,2015-08-30,1.38,83731.42,1406.11,61600.62,241.67,20483.02,20483.02,0.00,0.00,conventional,2015,BuffaloRochester
278,2015-08-23,1.49,68953.29,1287.09,43655.31,170.47,23840.42,23840.42,0.00,0.00,conventional,2015,BuffaloRochester
279,2015-08-16,1.50,69798.09,1230.78,45937.58,258.00,22371.73,22371.73,0.00,0.00,conventional,2015,BuffaloRochester
280,2015-08-09,1.47,81830.13,1139.74,56289.28,349.19,24051.92,24051.92,0.00,0.00,conventional,2015,BuffaloRochester
281,2015-08-02,1.47,78162.92,1447.81,44620.70,471.55,31622.86,31622.86,0.00,0.00,conventional,2015,BuffaloRochester
282,2015-07-26,1.39,91825.07,1679.28,45615.48,741.77,43788.54,43788.54,0.00,0.00,conventional,2015,BuffaloRochester
283,2015-07-19,1.36,128846.15,1165.75,54492.85,2205.14,70982.41,70982.41,0.00,0.00,conventional,2015,BuffaloRochester
284,2015-07-12,1.45,127351.46,1119.38,47294.67,4714.73,74222.68,73796.01,426.67,0.00,conventional,2015,BuffaloRochester
285,2015-07-05,1.47,140413.90,1503.10,56925.46,6707.85,75277.49,74370.82,906.67,0.00,conventional,2015,BuffaloRochester
286,2015-06-28,1.36,137246.70,1235.69,51801.73,5397.32,78811.96,78749.74,62.22,0.00,conventional,2015,BuffaloRochester
287,2015-06-21,1.50,108655.36,1254.83,47845.57,5424.52,54130.44,54130.44,0.00,0.00,conventional,2015,BuffaloRochester
289,2015-06-07,1.38,130908.11,779.02,57999.61,138.81,71990.67,71990.67,0.00,0.00,conventional,2015,BuffaloRochester
290,2015-05-31,1.40,130841.08,1039.49,54249.06,79.38,75473.15,75473.15,0.00,0.00,conventional,2015,BuffaloRochester
291,2015-05-24,1.43,121942.61,1033.76,55018.95,103.94,65785.96,65741.52,44.44,0.00,conventional,2015,BuffaloRochester
294,2015-05-03,1.42,136771.79,946.38,50266.22,81.86,85477.33,84332.05,1102.22,43.06,conventional,2015,BuffaloRochester
295,2015-04-26,1.41,136964.30,1117.56,49556.91,106.40,86183.43,85503.15,640.00,40.28,conventional,2015,BuffaloRochester
296,2015-04-19,1.42,139612.52,1021.72,52954.82,59.18,85576.80,85056.94,519.86,0.00,conventional,2015,BuffaloRochester
297,2015-04-12,1.42,118172.53,884.02,45443.61,92.75,71752.15,70938.40,813.75,0.00,conventional,2015,BuffaloRochester
298,2015-04-05,1.44,124145.62,969.27,51023.86,95.69,72056.80,71408.88,597.92,50.00,conventional,2015,BuffaloRochester
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18219,2018-02-11,1.56,1317000.47,98465.26,270798.27,1839.80,945638.02,768242.42,177144.00,251.60,organic,2018,TotalUS
18220,2018-02-04,1.53,1384683.41,117922.52,287724.61,1703.52,977084.84,774695.74,201878.69,510.41,organic,2018,TotalUS
18221,2018-01-28,1.61,1336979.09,118616.17,280080.34,1270.61,936859.49,796104.27,140652.84,102.38,organic,2018,TotalUS
18222,2018-01-21,1.63,1283987.65,108705.28,259172.13,1490.02,914409.26,710654.40,203526.59,228.27,organic,2018,TotalUS
18223,2018-01-14,1.59,1476651.08,145680.62,323669.83,1580.01,1005593.78,858772.69,146808.97,12.12,organic,2018,TotalUS
18224,2018-01-07,1.51,1517332.70,129541.43,296490.29,1289.07,1089861.24,915452.78,174381.57,26.89,organic,2018,TotalUS
18225,2018-03-25,1.60,271723.08,26996.28,77861.39,117.56,166747.85,87108.00,79495.39,144.46,organic,2018,West
18226,2018-03-18,1.73,210067.47,33437.98,47165.54,110.40,129353.55,73163.12,56020.24,170.19,organic,2018,West
18227,2018-03-11,1.63,264691.87,27566.25,60383.57,276.42,176465.63,107174.93,69290.70,0.00,organic,2018,West
18228,2018-03-04,1.46,347373.17,25990.60,71213.19,79.01,250090.37,85835.17,164087.33,167.87,organic,2018,West
18229,2018-02-25,1.49,301985.61,34200.18,49139.34,85.58,218560.51,99989.62,118314.77,256.12,organic,2018,West
18230,2018-02-18,1.64,224798.60,30149.00,38800.64,123.13,155725.83,120428.13,35257.73,39.97,organic,2018,West
18231,2018-02-11,1.47,275248.53,24732.55,61713.53,243.00,188559.45,88497.05,99810.80,251.60,organic,2018,West
18232,2018-02-04,1.41,283378.47,22474.66,55360.49,133.41,205409.91,70232.59,134666.91,510.41,organic,2018,West
18233,2018-01-28,1.80,185974.53,22918.40,33051.14,93.52,129911.47,77822.23,51986.86,102.38,organic,2018,West
18234,2018-01-21,1.83,189317.99,27049.44,33561.32,439.47,128267.76,76091.99,51947.50,228.27,organic,2018,West
18235,2018-01-14,1.82,207999.67,33869.12,47435.14,433.52,126261.89,89115.78,37133.99,12.12,organic,2018,West
18236,2018-01-07,1.48,297190.60,34734.97,62967.74,157.77,199330.12,103761.55,95544.39,24.18,organic,2018,West
18237,2018-03-25,1.62,15303.40,2325.30,2171.66,0.00,10806.44,10569.80,236.64,0.00,organic,2018,WestTexNewMexico
18238,2018-03-18,1.56,15896.38,2055.35,1499.55,0.00,12341.48,12114.81,226.67,0.00,organic,2018,WestTexNewMexico
18239,2018-03-11,1.56,22128.42,2162.67,3194.25,8.93,16762.57,16510.32,252.25,0.00,organic,2018,WestTexNewMexico
18240,2018-03-04,1.54,17393.30,1832.24,1905.57,0.00,13655.49,13401.93,253.56,0.00,organic,2018,WestTexNewMexico
18241,2018-02-25,1.57,18421.24,1974.26,2482.65,0.00,13964.33,13698.27,266.06,0.00,organic,2018,WestTexNewMexico
18242,2018-02-18,1.56,17597.12,1892.05,1928.36,0.00,13776.71,13553.53,223.18,0.00,organic,2018,WestTexNewMexico
18243,2018-02-11,1.57,15986.17,1924.28,1368.32,0.00,12693.57,12437.35,256.22,0.00,organic,2018,WestTexNewMexico
18244,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.00,organic,2018,WestTexNewMexico
18245,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.00,organic,2018,WestTexNewMexico
18246,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.00,organic,2018,WestTexNewMexico
18247,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.00,organic,2018,WestTexNewMexico
18248,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.00,organic,2018,WestTexNewMexico

In [24]:
df.loc[25:30]

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
25,2015-07-05,1.35,109252.12,869.45,72600.55,5883.16,29898.96,29663.19,235.77,0.0,conventional,2015,Albany
26,2015-06-28,1.37,89534.81,664.23,57545.79,4662.71,26662.08,26311.76,350.32,0.0,conventional,2015,Albany
27,2015-06-21,1.27,104849.39,804.01,76688.55,5481.18,21875.65,21662.00,213.65,0.0,conventional,2015,Albany
28,2015-06-14,1.32,89631.30,850.58,55400.94,4377.19,29002.59,28343.14,659.45,0.0,conventional,2015,Albany
29,2015-06-07,1.07,122743.06,656.71,99220.82,90.32,22775.21,22314.99,460.22,0.0,conventional,2015,Albany
30,2015-05-31,1.23,95123.62,922.37,70469.69,50.55,23681.01,23222.49,458.52,0.0,conventional,2015,Albany

In [26]:
df[(df['AveragePrice'] > 1.35) & (df['AveragePrice'] < 1.45) ]

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
26,2015-06-28,1.37,89534.81,664.23,57545.79,4662.71,26662.08,26311.76,350.32,0.00,conventional,2015,Albany
32,2015-05-17,1.43,109857.47,1150.55,81955.16,94.32,26657.44,26285.43,372.01,0.00,conventional,2015,Albany
261,2015-12-20,1.37,90867.51,1164.92,38430.71,106.67,51165.21,51165.21,0.00,0.00,conventional,2015,BuffaloRochester
264,2015-11-29,1.39,79973.14,1514.69,35682.71,113.49,42662.25,42662.25,0.00,0.00,conventional,2015,BuffaloRochester
265,2015-11-22,1.40,90242.31,1711.77,38780.66,107.53,49642.35,49642.35,0.00,0.00,conventional,2015,BuffaloRochester
266,2015-11-15,1.36,99703.72,1803.78,41457.12,107.48,56335.34,55593.12,742.22,0.00,conventional,2015,BuffaloRochester
269,2015-10-25,1.36,99554.55,1545.57,36645.91,79.64,61283.43,59381.21,1902.22,0.00,conventional,2015,BuffaloRochester
277,2015-08-30,1.38,83731.42,1406.11,61600.62,241.67,20483.02,20483.02,0.00,0.00,conventional,2015,BuffaloRochester
282,2015-07-26,1.39,91825.07,1679.28,45615.48,741.77,43788.54,43788.54,0.00,0.00,conventional,2015,BuffaloRochester
283,2015-07-19,1.36,128846.15,1165.75,54492.85,2205.14,70982.41,70982.41,0.00,0.00,conventional,2015,BuffaloRochester
286,2015-06-28,1.36,137246.70,1235.69,51801.73,5397.32,78811.96,78749.74,62.22,0.00,conventional,2015,BuffaloRochester
289,2015-06-07,1.38,130908.11,779.02,57999.61,138.81,71990.67,71990.67,0.00,0.00,conventional,2015,BuffaloRochester
290,2015-05-31,1.40,130841.08,1039.49,54249.06,79.38,75473.15,75473.15,0.00,0.00,conventional,2015,BuffaloRochester
291,2015-05-24,1.43,121942.61,1033.76,55018.95,103.94,65785.96,65741.52,44.44,0.00,conventional,2015,BuffaloRochester
294,2015-05-03,1.42,136771.79,946.38,50266.22,81.86,85477.33,84332.05,1102.22,43.06,conventional,2015,BuffaloRochester
295,2015-04-26,1.41,136964.30,1117.56,49556.91,106.40,86183.43,85503.15,640.00,40.28,conventional,2015,BuffaloRochester
296,2015-04-19,1.42,139612.52,1021.72,52954.82,59.18,85576.80,85056.94,519.86,0.00,conventional,2015,BuffaloRochester
297,2015-04-12,1.42,118172.53,884.02,45443.61,92.75,71752.15,70938.40,813.75,0.00,conventional,2015,BuffaloRochester
298,2015-04-05,1.44,124145.62,969.27,51023.86,95.69,72056.80,71408.88,597.92,50.00,conventional,2015,BuffaloRochester
299,2015-03-29,1.39,119890.65,1352.63,48430.03,80.52,70027.47,69919.00,108.47,0.00,conventional,2015,BuffaloRochester
300,2015-03-22,1.40,119902.96,3090.55,45420.06,48.20,71344.15,71288.59,55.56,0.00,conventional,2015,BuffaloRochester
303,2015-03-01,1.43,112363.86,1032.92,41685.04,104.16,69541.74,69479.52,62.22,0.00,conventional,2015,BuffaloRochester
304,2015-02-22,1.41,109546.92,1709.23,45393.96,131.72,62312.01,61765.34,546.67,0.00,conventional,2015,BuffaloRochester
305,2015-02-15,1.44,100207.14,1520.76,43271.55,57.76,55357.07,55232.63,124.44,0.00,conventional,2015,BuffaloRochester
306,2015-02-08,1.36,132760.10,1822.41,66261.92,161.96,64513.81,63918.25,595.56,0.00,conventional,2015,BuffaloRochester
311,2015-01-04,1.40,116253.44,3267.97,55693.04,109.55,57182.88,57182.88,0.00,0.00,conventional,2015,BuffaloRochester
761,2015-05-10,1.36,159642.82,7383.85,84947.73,3817.57,63493.67,59129.49,4335.74,28.44,conventional,2015,GrandRapids
895,2015-10-11,1.38,264227.78,4555.33,206738.06,491.68,52442.71,49064.30,3378.41,0.00,conventional,2015,HartfordSpringfield
919,2015-04-26,1.36,277178.42,4159.50,206008.87,229.90,66780.15,64008.53,2693.84,77.78,conventional,2015,HartfordSpringfield
925,2015-03-15,1.40,225761.68,6740.23,150490.66,160.54,68370.25,65306.48,3063.77,0.00,conventional,2015,HartfordSpringfield
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18064,2018-02-04,1.41,16592.21,352.86,3254.90,50.98,12933.47,12581.65,351.82,0.00,organic,2018,RichmondNorfolk
18065,2018-01-28,1.44,15001.51,422.41,3934.40,93.87,10550.83,9656.85,893.98,0.00,organic,2018,RichmondNorfolk
18075,2018-02-11,1.44,8863.94,115.82,1767.70,0.00,6980.42,5962.17,1018.25,0.00,organic,2018,Roanoke
18114,2018-01-21,1.36,27919.45,13037.67,11998.44,0.00,2883.34,2883.34,0.00,0.00,organic,2018,SanFrancisco
18121,2018-02-25,1.36,105545.72,1285.80,23264.24,41.54,80954.14,2511.78,78344.09,98.27,organic,2018,Seattle
18129,2018-03-25,1.38,16025.20,163.55,4234.24,81.45,11545.96,9882.44,1663.52,0.00,organic,2018,SouthCarolina
18131,2018-03-11,1.36,17561.89,181.68,4942.56,99.85,12337.80,11957.70,380.10,0.00,organic,2018,SouthCarolina
18132,2018-03-04,1.44,16468.01,206.20,5412.80,71.81,10777.20,9893.94,883.26,0.00,organic,2018,SouthCarolina
18133,2018-02-25,1.41,17191.34,212.48,4438.03,95.27,12445.56,12088.07,357.49,0.00,organic,2018,SouthCarolina
18134,2018-02-18,1.43,15443.91,145.58,4665.80,78.05,10554.48,9900.82,653.66,0.00,organic,2018,SouthCarolina
18136,2018-02-04,1.42,16666.13,132.57,4063.83,102.86,12366.87,11819.92,546.95,0.00,organic,2018,SouthCarolina
18138,2018-01-21,1.40,17566.45,105.95,4280.36,73.29,13106.85,11152.35,1954.50,0.00,organic,2018,SouthCarolina
18141,2018-03-25,1.42,163496.70,29253.30,5080.04,0.00,129163.36,109052.26,20111.10,0.00,organic,2018,SouthCentral
18144,2018-03-04,1.41,144664.26,25407.12,5094.72,0.00,114162.42,96833.15,17329.27,0.00,organic,2018,SouthCentral
18145,2018-02-25,1.41,126906.61,20045.22,4781.58,0.00,102079.81,87202.79,14877.02,0.00,organic,2018,SouthCentral
18146,2018-02-18,1.42,134888.08,23406.88,5128.16,27.46,106325.58,94331.46,11994.12,0.00,organic,2018,SouthCentral
18147,2018-02-11,1.40,128955.64,20164.54,3290.73,0.00,105500.37,93391.83,12108.54,0.00,organic,2018,SouthCentral
18148,2018-02-04,1.41,135996.73,29097.18,3815.01,0.00,103084.54,96116.60,6967.94,0.00,organic,2018,SouthCentral
18149,2018-01-28,1.42,137453.79,29301.71,4418.91,0.00,103733.17,98629.14,5104.03,0.00,organic,2018,SouthCentral
18150,2018-01-21,1.44,138349.93,22596.66,3200.09,0.00,112553.18,105354.48,7198.70,0.00,organic,2018,SouthCentral
18152,2018-01-07,1.41,126323.33,25296.77,3848.62,3.00,97174.94,90151.57,7023.37,0.00,organic,2018,SouthCentral
18154,2018-03-18,1.43,119853.94,2557.74,20398.98,133.09,96764.13,82917.28,13846.85,0.00,organic,2018,Southeast
18155,2018-03-11,1.37,113559.93,2019.57,19238.35,130.10,92171.91,89311.39,2860.52,0.00,organic,2018,Southeast
18160,2018-02-04,1.44,96702.50,1589.03,16827.96,118.89,78166.62,72587.74,5578.88,0.00,organic,2018,Southeast
18163,2018-01-14,1.42,106345.74,1053.73,16596.47,158.66,88536.88,78949.63,9587.25,0.00,organic,2018,Southeast
18164,2018-01-07,1.40,103034.09,1359.47,16209.36,194.07,85271.19,78886.47,6384.72,0.00,organic,2018,Southeast
18192,2018-03-04,1.42,3061.66,395.14,89.31,0.00,2577.21,721.50,1855.71,0.00,organic,2018,Syracuse
18201,2018-03-25,1.41,10028.49,138.15,773.22,0.00,9117.12,8208.82,908.30,0.00,organic,2018,Tampa
18205,2018-02-25,1.37,9144.20,206.39,542.89,0.00,8394.92,7895.92,499.00,0.00,organic,2018,Tampa
18232,2018-02-04,1.41,283378.47,22474.66,55360.49,133.41,205409.91,70232.59,134666.91,510.41,organic,2018,West

In [28]:
df.sort_values('Date',inplace=True)
df.head()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
11569,2015-01-04,1.75,27365.89,9307.34,3844.81,615.28,13598.46,13061.10,537.36,0.0,organic,2015,Southeast
9593,2015-01-04,1.49,17723.17,1189.35,15628.27,0.00,905.55,905.55,0.00,0.0,organic,2015,Chicago
10009,2015-01-04,1.68,2896.72,161.68,206.96,0.00,2528.08,2528.08,0.00,0.0,organic,2015,HarrisburgScranton
1819,2015-01-04,1.52,54956.80,3013.04,35456.88,1561.70,14925.18,11264.80,3660.38,0.0,conventional,2015,Pittsburgh
9333,2015-01-04,1.64,1505.12,1.27,1129.50,0.00,374.35,186.67,187.68,0.0,organic,2015,Boise